Check for missing Configuration file.

diff --git a/bin/refresh b/bin/refresh
--- a/bin/refresh
+++ b/bin/refresh
@@ -2,6 +2,11 @@
 
 # https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
 export DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd ".." && pwd )"
+
+if [ ! -r ${DIR}/Configuration ] ; then
+    echo "Cannot read Configuration file."
+    exit 1
+fi
 source ${DIR}/Configuration
 
 nargs=$#
@@ -208,7 +213,7 @@ if [ $nargs -eq 0 -o $domgi == T ]; then
 # MGI.gff3
 # Date: `date`
 # Taxonid: 10090
-# Genome build: GRCm38
+# Genome build: ${MOUSE_ASSEMBLY}
 #
 # The MGI gff3 file is generated by merging information from multiple sources.
 # Gene nomenclature, identifiers, and cross references come from MGI.
