Catch bad config file argument.

diff --git a/bin/refresh b/bin/refresh
--- a/bin/refresh
+++ b/bin/refresh
@@ -26,6 +26,10 @@ do
 	shift
 	echo "Sourcing config file:" $1
 	source $1
+        if [ $? -ne 0 ]; then
+            echo "Config file not found or not in correct format: $1"
+            exit 1
+        fi
 	nargs=$((nargs-2))
 	;;
     -n)
